Tebello.MimsWeb/Models/Basket.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;
using Subs.Data;

namespace Tebello.MimsWeb.Models
{
    public class Basket
    {
       public  ObservableCollection<BasketItem> BasketItems { get; set;}
       public bool RequiresDeliveryAddress{ get; set; }
       public decimal TotalPrice { get; set;}
       public decimal TotalDiscount { get; set; }
       public decimal TotalDiscountedPrice { get; set; }
       public int InvoiceId { get; set;} 

       public Basket()
       {
            BasketItems = new ObservableCollection<BasketItem>();

       }
    }
}

Tebello.MimsWeb/Controllers/PromotionController.cs
using Subs.Business;
using Subs.Data;
using Tebello.MimsWeb.Models;
using Tebello.Presentation;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading;
using System.Web.Mvc;

namespace Tebello.MimsWeb.Controllers
{
    public class PromotionController : Controller
    {
        private ProductData gProductData;
        private readonly MIMSDataContext gMIMSDataContext = new MIMSDataContext(Settings.ConnectionString);

        public PromotionController()
        {
            gProductData = new ProductData();
        }


        public ActionResult GetProducts(int ProductSelector = (int)WebProductClassifications.All)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.Message = ModelState.ToString();
                    return View("Error");
                }

                WebProducts lWebProducts = new WebProducts();
                lWebProducts.ProductSelector = ProductSelector;
                lWebProducts.Bulletin = NoteData.GetBulletin();
                LoginRequest lLoginRequest = SessionHelper.GetLoginRequest(Session);

                lWebProducts.ListOfWebProducts = gProductData.WebProducts(lWebProducts.ProductSelector);


                if (lWebProducts.ListOfWebProducts.Count() == 0)
                {
                    ViewBag.Message = "Sorry, no product satisfies these requirements";
                    return View("List", lWebProducts);
                }
                else
                {
                    if (lLoginRequest.CustomerId != null)
                    {
                        foreach (WebProduct item in lWebProducts.ListOfWebProducts)
                        {
                            item.Price = SubscriptionBiz.StandardProductPrice(item.ProductId, (int)lLoginRequest.CustomerId);
                        }
                    }

                    // Save this as a session variable, and use it to populate the model.

                    SessionHelper.Set(Session, SessionKey.WebProducts, lWebProducts);

                    return View("List", lWebProducts);   //
                }
            }

            catch (Exception ex)
            {
                //Display all the exceptions

                Exception CurrentException = ex;
                int ExceptionLevel = 0;
                do
                {
                    ExceptionLevel++;
                    ExceptionData.WriteException(1, ExceptionLevel.ToString() + " " + CurrentException.Message, this.ToString(), "GetProducts - post", "");
                    CurrentException = CurrentException.InnerException;
                } while (CurrentException != null);

                ViewBag.Message = ex.Message;

                return View("Error");
            }
        }



        [HttpGet]
        public ViewResult List()
        {

            //Silke insisted that the page where you query what category to select from and the view where you display the products, be the same page.
            //Hence, this view can operate in two modes. The first is just a query, and the second is the query plus the result.

            try
            {

                WebProducts lPreviousSelection = SessionHelper.GetWebProducts(Session);

                //22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222


                // Add the original prices if the user has logged in in the mean time.

                LoginRequest lLoginRequest = SessionHelper.GetLoginRequest(Session);
                if (lLoginRequest.CustomerId != null && lPreviousSelection.ListOfWebProducts != null)
                {
                    foreach (WebProduct item in lPreviousSelection.ListOfWebProducts)
                    {
                        item.Price = SubscriptionBiz.StandardProductPrice(item.ProductId, (int)lLoginRequest.CustomerId);
                    }
                }

                return View("List", lPreviousSelection);

                //22222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222222
            }

            catch (Exception ex)
            {
                //Display all the exceptions

                Exception CurrentException = ex;
                int ExceptionLevel = 0;
                do
                {
                    ExceptionLevel++;
                    ExceptionData.WriteException(1, ExceptionLevel.ToString() + " " + CurrentException.Message, this.ToString(), "List", "");
                    CurrentException = CurrentException.InnerException;
                } while (CurrentException != null);

                ViewBag.Message = ex.Message;

                return View("Error");
            }
        }


        public ActionResult GoToBasket()
        {
            if (SessionHelper.GetLoginRequest(Session).CustomerId == null)
            {
                ViewBag.Message = "You cannot have a basket if you are not logged in first";
                return View("List");
            }

            Basket lBasket;
            lBasket = SessionHelper.GetBasket(Session);
            if (lBasket.BasketItems.Count == 0)
            {
                ViewBag.Message = "Your basket is empty";
                return View("List");
            }

            if (lBasket.BasketItems.Count() == 1)
            {
                ViewBag.Message = "There is " + lBasket.BasketItems.Count() + " product selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
            }
            else
            {
                ViewBag.Message = "There are " + lBasket.BasketItems.Count() + " products selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
            }

            return View("Basket", lBasket);
        }

        public ActionResult AddToBasket(int ProductId)
        {
            string lStage = "GetBasket";

            Basket lBasket = SessionHelper.GetBasket(Session);

            try
            {
                if (lBasket == null)
                {
                    lBasket = new Basket();
                }

                // If there is one already, add to units per issue

                bool lFound = false;
                foreach (BasketItem item in lBasket.BasketItems)
                {
                    if (item.Subscription.ProductId == ProductId)
                    {
                        lFound = true;
                        item.Subscription.UnitsPerIssue++;
                    }
                }

                lStage = "Found?";

                if (!lFound)
                {
                    // create a new BasketItem
                    LoginRequest lLoginRequest = SessionHelper.GetLoginRequest(Session);


                    SubscriptionData3 lSubscription = new SubscriptionData3();

                    lSubscription.PayerId = (int)lLoginRequest.CustomerId;
                    lSubscription.ReceiverId = (int)lLoginRequest.CustomerId;
                    lSubscription.ProductId = ProductId;
                    DateTime lNextDate;

                    {
                        string lResult;
                        if ((lResult = SubscriptionBiz.NextDate((int)lLoginRequest.CustomerId, ProductId, out lNextDate)) != "OK")
                        {
                            ViewBag.Message = lResult;
                            return View("Basket", lBasket);
                        }
                    }

                    {
                        MimsValidationResult lResult = SubscriptionBiz.SetInitialValues(lSubscription, lNextDate);

                        if (lResult.Message != "OK" && !lResult.Prompt)
                        {
                            ViewBag.Message = lResult.Message;
                            return View("Basket", lBasket);
                        }
                    }

                    BasketItem lBasketItem = new BasketItem() { Subscription = lSubscription };
                    lBasketItem.ProductName = ProductDataStatic.GetProductName(ProductId);
                    lBasket.BasketItems.Add(lBasketItem);

                    lStage = "Calculate";


                    if (SubscriptionBiz.CalculateBasket(lBasket.BasketItems))
                    {
                        lBasket.TotalPrice = 0;
                        lBasket.TotalDiscount = 0;
                        lBasket.TotalDiscountedPrice = 0;


                        foreach (BasketItem item in lBasket.BasketItems)
                        {
                            lBasket.TotalPrice += item.Price;
                            lBasket.TotalDiscount += item.Discount;
                        }

                        lBasket.TotalDiscountedPrice = lBasket.TotalPrice - lBasket.TotalDiscount;

                        if (lBasket.BasketItems.Count() == 1)
                        {
                            ViewBag.Message = "There is " + lBasket.BasketItems.Count() + " product selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
                        }
                        else
                        {
                            ViewBag.Message = "There are " + lBasket.BasketItems.Count() + " products selected, resulting in a price of " + lBasket.TotalDiscountedPrice.ToString("R #####0.00");
                        }
                    }
                    else
                    {
                        ViewBag.Message = "There was a problem calculating the basket value";
                        return View("Empty");
                    }
                }

                lStage = "Set";

                SessionHelper.Set(Session, SessionKey.Basket, lBasket);
                return View("Basket", lBasket);
            }
            catch (Exception ex)

Tebello.MimsWeb/Views/Promotion/Basket.cshtml
@using Subs.Data;
@using Subs.Business;
@using Tebello.MimsWeb.Models;
@using System.Collections.ObjectModel;

@model Basket

@{
    ViewBag.Title = "Basket";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="/Content/normalise.css">
    <link rel="stylesheet" href="/Content/Styles.css">
    <script src="/Scripts/jquery-3.4.1.js"></script>
    <script src="/Scripts/Default.js"></script>

    <title>Cart</title>
    <style>
        p {
            margin: 2em 1em 1em 1em;
            color: red;
        }

        th, td {
            padding: 1em 1em 1em 0.5em;
            text-anchor: start;
            text-align: left;
        }

        .myButtons button {
            margin: 1em 0em 0em 0em;
            display: inline;
            padding: 0px 7px 1px 7px;
            border-radius: 10px;
            text-decoration: none;
            text-shadow: none;
            font-family: Titillium, Arial, sans-serif;
            font-weight: 700;
            color: white;
            text-transform: capitalize;
            font-size: 0.8em;
            letter-spacing: .1em;
            background-color: dodgerblue;
        }


        .myButtons a {
            margin: 2em 0em 0em 1em;
            display: inline;
            padding: 0px 7px 1px 7px;
            border-radius: 10px;
            text-decoration: none;
            font-family: Titillium, Arial, sans-serif;
            font-weight: 700;
            color: white;
            text-transform: capitalize;
            font-size: 1.5em;
            letter-spacing: .1em;
            background-color: dodgerblue;
        }

        .myTotals {
            padding: 1em 1em 1em 0.5em;
            border-top: 1px solid black;
            border-bottom: 2px solid black;
        }


        .NumberStyle {
            text-align: right;
        }
    </style>
</head>
<body>
    <p>
        @Html.ViewBag.Message
    </p>

    <p id="gMessage" style="visibility: hidden;">
    </p>

    @using (Html.BeginForm("BasketModification", "Promotion", FormMethod.Post, new { id = "SubmitForm" }))
    {
        <div class="myButtons" margin-left="0.5em">
            @Html.ActionLink("Finalise Your Order", "Submit", "Promotion",
                    new { onclick = "return window.confirm('Are you sure that you want to submit these subscriptions ?')" })
            @Html.ActionLink("Continue shopping", "List", "Promotion", new { display = "inline" })

        </div>

        <table>
            <tr>
                <th>Remove</th>
                <th>Product</th>
                <th onmouseover="ShowMessage('One can have more than one copy of a product per issue.')" onmouseleave="HideMessage()"> # of copies</th>
                <th> #Issues</th>
                <th> Delivery option</th>
                <th> Delivery cost</th>
                <th> VAT</th>
                <th> Full price</th>
                <th> Discount</th>
                <th> Final price</th>
                <th></th>
            </tr>
            @{
                int i = 0;
                string lUnitsPerIssue = "";
                string lDropBox = "";

                foreach (BasketItem p in Model.BasketItems)
                {
                    lUnitsPerIssue = "[" + i + "].UnitsPerIssue";
                    lDropBox = "[" + i + "].Drop";
                    <tr>
                        <td>@Html.CheckBox(@lDropBox, false, new { onchange = "ModificationHandler()" })</td>
                        <td>@p.ProductName </td>
                        <td style="width:3em">
                            <input class="NumberStyle" onchange="ModificationHandler()" type="number" name=@lUnitsPerIssue value=@p.Subscription.UnitsPerIssue
                                   min="1" max="10000" step="1" />
                        </td>

                        <td style="text-align:right;width:3em">@p.Subscription.NumberOfIssues </td>
                        <td>
                            @Html.DropDownList("[" + i + "].DeliveryMethod", new SelectList(p.DeliveryOptions, "Key", "Value", p.Subscription.DeliveryMethodInt),
                                                new Dictionary<string, object> { { "selected", p.Subscription.DeliveryMethodInt }, { "onchange", "ModificationHandler()" } })
                        </td>

                        <td style="text-align:right">@p.Subscription.DeliveryCost.ToString("####0.00") </td>

                        <td style="text-align:right">@p.Subscription.Vat.ToString("####0.00") </td>

                        <td style="text-align:right">@p.Price.ToString("####0.00") </td>
                        <td style="text-align:right">@p.Discount.ToString("####0.00") </td>
                        <td style="text-align:right">@p.DiscountedPrice.ToString("######0.00") </td>
                        <td style="text-align:right;color:red">@p.Warning</td>
                    </tr>
                    i++;

                }
            }
            <tr>
                <td class="myTotals"><strong>Totals</strong></td>
                <td class="myTotals"> </td>
                <td class="myTotals" colspan="5"> </td>
                <td class="myTotals" style="text-align:right">@Model.TotalPrice.ToString("########0.00") </td>
                <td class="myTotals" style="text-align:right">@Model.TotalDiscount.ToString("########0.00") </td>
                <td class="myTotals" style="text-align:right">@Model.TotalDiscountedPrice.ToString("########0.00") </td>

            </tr>
            <tr> </tr>
        </table>
        <script>
            function ModificationHandler() {
                document.forms["SubmitForm"].submit();
            }

            function ShowMessage(m) {
                var lElement = document.getElementById('gMessage');
                lElement.textContent = m;
                lElement.style.visibility = 'visible';
            }

            function HideMessage() {
                document.getElementById('gMessage').style.visibility = 'hidden';
            }


        </script>
    } @*end of form*@

</body>
</html>

Tebello.MimsWeb/Views/Promotion/DeliveryAddress.cshtml
@using Tebello.MimsWeb.Models;

@model DeliveryAddressTemplate
@{
    ViewBag.Title = "DeliveryAddress";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="/Content/normalise.css">
    <link rel="stylesheet" href="/Content/Styles.css">

    <title>DeliveryAddress</title>

    <style>

        .editor-label, .editor-field {
            float: left;
            margin-top: 10px;
            margin-left: 1em;
            height: 20px
        }

            .editor-field input {
                width: 200px;
            }

        .editor-label {
            clear: left;
            display: inline-block;
            width: 120px;
            font-family: Arial;
        }

        .myButtons li {
            display: inline;
        }

        .myButtons button {
            display: inline;
            padding: 0px 7px 1px 7px;
            border-radius: 10px;
            text-decoration: none;
            text-shadow: none;
            font-family: Titillium, Arial, sans-serif;
            font-weight: 700;
            color: white;
            text-transform: capitalize;
            font-size: 0.8em;
            letter-spacing: .1em;
            background-color: dodgerblue;
        }

        label {
            display: inline-block;
            width: 200px;
            font-family: Arial;
        }

        .dataElem {
            margin: 0.5em 0.5em 0.5em 1em;
        }

            .dataElem input {
                width: 30em;
            }

            .dataElem select {
                width: 30em;
            }
    </style>

</head>
<body>
    <p style="padding:1em 1em 0em 1em">
        @Html.ViewBag.Message
    </p>

    <p>
        @Html.ValidationSummary()
    </p>

    @using (Html.BeginForm("DeliveryAddress", "Promotion"))
    {
        <div class="myButtons">
            <ul>
                <li><button type="submit">Confirm the delivery address</button></li>
            </ul>
        </div>

        <fieldset style="margin: 1em 0em 0em 0.6em;">

            
            <div class="dataElem">
                @Html.LabelFor(x => x.CountryId)
                @Html.DropDownListFor(x => x.CountryId, @Model.CountrySelectList, new Dictionary<string, object>() { { "style", "width:154px" } })
            </div>


            <div class="dataElem">
                @Html.LabelFor(x => x.Province)
                @Html.EditorFor(x => x.Province)
            </div>

            <div class="dataElem">
                @Html.LabelFor(x => x.City)
                @Html.EditorFor(x => x.City)
            </div>

            <div class="dataElem">
                @Html.LabelFor(x => x.Suburb)
                @Html.EditorFor(x => x.Suburb)
            </div>


            <div class="dataElem">
                @Html.LabelFor(x => x.Street)
                @Html.EditorFor(x => x.Street)
            </div>

            <div class="dataElem">
                @Html.LabelFor(x => x.StreetExtension)
                @Html.EditorFor(x => x.StreetExtension)
            </div>

            <div class="dataElem">
                @Html.LabelFor(x => x.StreetSuffix)
                @Html.EditorFor(x => x.StreetSuffix)
            </div>
            <div class="dataElem">
                @Html.LabelFor(x => x.StreetNo)
                @Html.EditorFor(x => x.StreetNo)
            </div>
            <div class="dataElem">
                @Html.LabelFor(x => x.Building)
                @Html.EditorFor(x => x.Building)
            </div>
            <div class="dataElem">
                @Html.LabelFor(x => x.Floor)
                @Html.EditorFor(x => x.Floor)
            </div>
            <div class="dataElem">
                @Html.LabelFor(x => x.Room)
                @Html.EditorFor(x => x.Room)
            </div>
            <div class="dataElem">
                @Html.LabelFor(x => x.PostCode)
                @Html.EditorFor(x => x.PostCode)
            </div>
        </fieldset>

    }
</body>
</html>

Tebello.MimsWeb/Views/Promotion/List.cshtml
@using Subs.Data
@using Tebello.MimsWeb.Models;
@using System.Web;
@model Subs.Data.WebProducts



@{
    ViewBag.Title = "ProductCatalog";
    Html.EnableClientValidation(false);  // p619
}

@helper ProductMenu()
{
    <br />
    <p class="Menu">@Html.ActionLink("ALL PRODUCTS", "GetProducts", new { ProductSelector = (Math.Log((int)WebProductClassifications.All, 2) + 1).ToString("#0") })</p>
    <br />
    <p>MEDICINES INFORMATION</p>
    <p class="Menu  SubItem">@Html.ActionLink("Prescription", "GetProducts", new { ProductSelector = (Math.Log((int)WebProductClassifications.Prescription, 2) + 1).ToString("#0") })</p>

    <p class="Menu SubItem">@Html.ActionLink("Over the counter", "GetProducts", new { ProductSelector = (Math.Log((int)WebProductClassifications.OverTheCounter, 2) + 1).ToString("#0") })</p>
    <p class="Menu  SubItem"> @Html.ActionLink("Competitive sport", "GetProducts", new { ProductSelector = (Math.Log((int)WebProductClassifications.CompetitiveSport, 2) + 1).ToString("#0") })</p>
    <br />
    <p class="Menu"> @Html.ActionLink("TREATMENT APPROACHES", "GetProducts", new { ProductSelector = (Math.Log((int)WebProductClassifications.TreatmentApproaches, 2) + 1).ToString("#0") })</p>
    <br />
    <p class="Menu">@Html.ActionLink("VETERINARY MEDICINE", "GetProducts", new { ProductSelector = (Math.Log((int)WebProductClassifications.VeterinaryMedicine, 2) + 1).ToString("#0") })</p>
}



@*Silke insisted that the page where you query what category to select from and the view where you display the products, be the same page.
    Hence, this view can operate in two modes. The first is just a query, and the second is the query plus the result.*@

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no">
    <script src="/Scripts/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="/Content/normalise.css">
    <link rel="stylesheet" href="/Content/Styles.css">
    <title>@ViewBag.Title</title>

    <style>

        textarea {
            text-align: center;
            font-size: medium;
            border: none;
            resize: none;
        }

        .Comparison1 td {
            border: 1px solid gray;
            margin: 0;
            color: black;
        }

        .Comparison1 th {
            border: 1px solid gray;
            margin: 0;
            color: black;
        }

            .Comparison1 td:nth-child(2), .Comparison1 th:nth-child(2) {
                background-color: rgb(240,248,255,255);
            }

            .Comparison1 td:nth-child(3), .Comparison1 th:nth-child(3) {
                background-color: rgb(245,253,255,255);
            }

            .Comparison1 td:nth-child(n+4), .Comparison1 th:nth-child(n+4) {
                background-color: rgb(240,248,255,255);
            }

        .blokcontainer {
            display: flex;
            flex-flow: row wrap;
        }

        .insideblokcontainer {
            display: flex;
            flex-flow: row wrap;
            justify-content: center;
            align-items: center;
            border: solid 1px lightgray;
            width: 200px;
            height: 350px;
            margin: 1em 1em 1em 1em;
            font-size: 14px;
        }

        .imageinblok {
            border: none;
            width: 150px;
            height: 200px;
        }

        .DescriptionStyle {
            visibility: hidden;
            width: 500px;
            background-color: white;
            color: #000;
            text-align: left;
            border-radius: 6px;
            border: 2px solid black;
            padding: 1em 1em 1em 1em;
            font: 12px;
            position: fixed;
            top: 4em;
            left: 20%;
            right: 20%;
            width: 60%;
        }


        p.Menu {
            margin-block-start: 0em;
            margin-block-end: 0em;
            width: 180px;
            color: black;
        }

        p.SubItem {
            text-indent: 10px;
        }


        a {
            text-decoration: none;
            color: black;
        }

            a:hover {
                color: lightskyblue;
            }


        .bulletin {
            display: flex;
            flex-flow: row wrap;
            justify-content: center;
            align-items: center;
            border: solid 1px lightgray;
            width: 200px;
            height: 160px;
            margin: 0em 1em 1em 0em;
            padding: 0em 1em 0em 1em;
            font-size: 14px;
        }




        #Narrow {
            display: none;
        }

        /*Phone*/
        @@media (max-width: 480px) {
            .blok {
                flex-flow: row wrap;
            }

            #Narrow {
                display: block;
            }

            #Wide {
                display: none;
            }
        }
    </style>

    <script>
        $(document).ready(function () {
            try {
                var lOptions = document.getElementsByTagName("option");
                var lSelectedCategoryId = document.getElementById("SelectedCategoryId").getAttribute("value");
                for (var i = 0; i < lOptions.length; i++) {
                    var lOption = lOptions[i];
                    if (lOption.value == lSelectedCategoryId) {
                        lOption.setAttribute("selected", "selected");
                    }
                }
            }
            catch (error) {
                console.log(error);
            }
        })
    </script>

</head>
<body>
    @using (Html.BeginForm("GetProducts", "Promotion", FormMethod.Post, new { id = "SelectLevel1" }))
    {

        <p style="color: red; margin:0em 1em 1em 1em">
            @Html.ViewBag.Message
        </p>



        if (Model == null)
        {
            <label type="hidden" id="SelectedCategoryId" value=1 />
        }
        else
        {
            <label type="hidden" id="SelectedCategoryId" value=@Model.ProductSelector />
        }

        if (Model != null)
        {
            if (Model.ProductSelector == Int32.Parse((Math.Log((int)WebProductClassifications.Prescription, 2) + 1).ToString("#0")))
            {
                @Html.Partial("MedicineComparison");
            }
        }

        <a class="GoToCart" href="/Promotion/GoToBasket" style="color:black; background-color:aqua; margin-left:1em">
            <div>
                @*<label style="margin-bottom:2em">Go to basket</label>*@
                <img display="inline" src="~/Images/shopping.png" height="50" width="50" />
            </div>
        </a>
        <br /><br />


        <table id="Narrow">
            <tr>
                <td valign="top">
                    @ProductMenu()
                </td>
            </tr>
        </table>

        <table>
            <tr>
                <td id="Wide" valign="top">
                    @ProductMenu()
                    <br />
                    <br />
                    <div class="bulletin">@Html.Raw(Model.Bulletin)</div>
                </td>

                <td>
                    <div class="blokcontainer">
                        @{
                            int i = 0;
                            if (Model != null)
                            {
                                foreach (WebProduct p in Model.ListOfWebProducts)
                                {
                                    <div class="insideblokcontainer">
                                        <textarea rows="3" cols="23" readonly style="font-size:14px;font-weight:500;" onmouseover="Describe(@i)" onmouseout="Undescribe(@i)">@p.Heading</textarea>

                                        <div class="imageinblok" onmouseover="Describe(@i)" onmouseout="Undescribe(@i)" style="background: url(data:jpeg;base64,@p.PictureAsString);background-size:100% 100%;">
                                        </div>

                                        <div class="DescriptionStyle" name="lDescription">
                                            @Html.Raw(p.ProductDescription)
                                        </div>


                                        @{
                                            LoginRequest lLoginRequest = SessionHelper.GetLoginRequest(Session);
                                            if (lLoginRequest.CustomerId != null)
                                            {
                                                <div>
                                                    <span style="font-weight:bold">@p.Price.ToString("R #####0.00")</span>
                                                    @if (p.CPDEnabled)
                                                    {
                                                        <label style="color:black; font-size:medium;font-weight:700; display:inline;margin-left:10px">with CPD</label>
                                                    }

                                                    <p> @Html.ActionLink("Add to cart", "AddToBasket", new { ProductId = p.ProductId })</p>

                                                </div>
                                            }
                                            else
                                            {
                                                <p>
                                                    <label class="DescriptionStyle" style="visibility:visible">
                                                        To order, please register and/or login first.
                                                    </label>

                                                </p>
                                            }
                                        }

                                        @Html.Hidden("[" + i + "].Heading", p.Heading)
                                        @Html.Hidden("[" + i + "].ProductId", p.ProductId)

                                    </div>
                                    i++;
                                }
                            }
                        }
                    </div>
                </td>
            </tr>
        </table>
    }

    <script>
        function SelectionHandler() {
            document.forms["SelectLevel1"].submit();
        }

        function Describe(i) {
            var Target = document.getElementsByName('lDescription')[i];
            Target.style.visibility = 'visible';
            Target.style.zIndex = 100;
        }

        function Undescribe(i) {
            var Target = document.getElementsByName('lDescription')[i];
            Target.style.visibility = 'hidden';
        }

    </script>
</body>
</html>